Add example data to new courses
hack4impact-uiuc/7000-languages pull request #223
Opened 2022-10-07 20:41 UTC by rustom

## Status: :construction: In development

## Description

Adds hardcoded example units, lessons, and vocab items to any new course that is created. Fixes #99.

## Todos
- [ ] Tests

## Screenshots

2022-10-12 01:56 UTC, ashayp22 requested changes
lfg

2022-10-12 01:56 UTC, ashayp22 commented on api/src/api/language/course.js
> +async function populateExampleData(course_id) {
to utils

2022-10-12 01:56 UTC, ashayp22 commented on api/src/api/language/course.js
> +    const order = await getNumUnitsInCourse(course_id);
break up modularize

2022-10-12 01:56 UTC, ashayp22 commented on api/src/api/language/course.js
> +    await newUnit.save();
check if unit id is valid

2022-10-12 01:56 UTC, ashayp22 commented on api/src/api/language/course.js
> +    await newUnit.save();
course id, my bad rustom

2022-10-18 01:21 UTC, ashayp22 commented on api/src/utils/languageHelper.js
> +async function checkIds({
wondering why you made this change

2022-10-18 02:24 UTC, rustom commented on api/src/utils/languageHelper.js
> +async function checkIds({
reverted

2022-10-18 06:04 UTC, ashayp22 approved these changes

2022-10-18 06:25 UTC, merged