Jamie/course settings UI
hack4impact-uiuc/7000-languages pull request #263
Opened 2022-11-04 02:38 UTC by jamieRollison

## Status:

:rocket: Ready

## Description

Made the course settings page.

Fixes #254 

## Todos

## Screenshots
![826E8494-AD3C-42BF-BA6E-F73C2096B928_1_101_o](https://user-images.githubusercontent.com/90640394/199872682-d0338d28-bd2f-49e8-abfe-3d6f707316cf.jpeg)

2022-11-04 03:03 UTC, eeshabarua requested changes
This looks so good! Except locally I'm getting this weird error but it might j be a my-computer thing
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/61480751/199875198-02f0d6c5-636c-4cc3-8e9e-7c1214b00a39.png">

2022-11-05 20:17 UTC, ashayp22 commented on client/src/pages/CourseSettings/CourseSettings.js
> +    marginHorizontal: '3%', // i think there's a better way to do this
Is this your comment? What exactly are you trying to achieve?

2022-11-05 20:26 UTC, ashayp22 requested changes
Looks great Jamie, I left a few inline comments. Main functional fix is to make sure that the Private Code Input Field is only shown when the Course is set to Private.

2022-11-05 20:26 UTC, ashayp22 commented on client/src/pages/CourseSettings/CourseSettings.js
> +        <Text fontFamily="heading" fontWeight="regular" fontSize="lg">
Make sure to only show the input field if the course is private.

2022-11-05 20:26 UTC, ashayp22 commented on client/src/pages/ManageVocab/ManageVocab.js
> +  //   const allVocab = lessonData.vocabs
+1

2022-11-05 20:26 UTC, ashayp22 commented on client/src/pages/ManageVocab/ManageVocab.js
> +        indicatorType: INDICATOR_TYPES.NONE, // TODO: remove hard-coded value
Comment should be good to remove since we no longer use indicator types

2022-11-05 22:27 UTC, ashayp22 approved these changes

2022-11-05 22:43 UTC, merged